-- Migration: Create Push Notification Subscriptions table
-- Copy and run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

DROP TABLE IF EXISTS public.push_subscriptions;

CREATE TABLE public.push_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id text REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    endpoint text UNIQUE NOT NULL,
    p256dh text NOT NULL,
    auth text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Disable Row Level Security (RLS) to align with Firebase Auth and anonymous connection setup
ALTER TABLE public.push_subscriptions DISABLE ROW LEVEL SECURITY;

